### ISSUE TITLE
Doesn't work with MacOS 10.13

### ISSUE THREAD

**Issue by whmountains** [wulkano/aperture#42]
Kap works fine, but when I try to use aperture directly I get this error:

```
/path/to/project/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 10.13
    at new SemVer (/path/to/project/node_modules/semver/semver.js:293:11)
    at compare (/path/to/project/node_modules/semver/semver.js:566:10)
    at Function.gte (/path/to/project/node_modules/semver/semver.js:615:10)
    at Function.x.isGreaterThanOrEqualTo.input [as isGreaterThanOrEqualTo] (/path/to/project/node_modules/macos-version/index.js:46:16)
    at Function.x.assertGreaterThanOrEqualTo.input [as assertGreaterThanOrEqualTo] (/path/to/project/node_modules/macos-version/index.js:56:9)
    at new Aperture (/path/to/project/node_modules/aperture/index.js:12:18)
    at module.exports (/path/to/project/node_modules/aperture/index.js:118:24)
    at Object.<anonymous> (/path/to/project/screencapture.js:2:37)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by whmountains** [comment]
Looks like this is a bug with the `macos-version` package.  Moving it to sindresorhus/macos-version/issues/4

**Comment by sindresorhus** [comment]
Fixed. Just reinstall `aperture`.

**Comment by whmountains** [comment]
That was fast!
